name: CI CD Pipeline

on:
  push:
    branches: [ "master", "feature-*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore BlazorWebAppGames.csproj

      - name: Lint check
        run: dotnet format BlazorWebAppGames.csproj --verify-no-changes

      - name: Build
        run: dotnet build BlazorWebAppGames.csproj --configuration Release --no-restore

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: blazorwebappgames-artifact
          path: bin/Release/
          if-no-files-found: error        

# Define a deploy to development environment job
  DeployDev:
    name: Deploy to Development
    # Job runs only if the event is a pull request
    if: github.event_name == 'pull_request'
    # The job needs the build job to pass first
    needs: [ Build ]
    runs-on: ubuntu-latest
    environment: 
      name: Development
    steps:
      - name: Deploy
        run: echo Your code is being deployed to Development
  
  # Our deployment to staging environment
  DeployStaging:
    name: Deploy to Staging
    # deploy to staging only if we are committing to main
    if: github.event.ref == 'refs/heads/master'
    needs: [ Build ]
    runs-on: ubuntu-latest
    environment:
      name: Staging
      url: 'http://test.myapp.com'
    steps:
    - name: Deploy
      run: echo I am deploying to staging 
  
  # Deploy to production environment
  DeployProduction:
    name: Deploy to Production
    needs: [DeployStaging]
    runs-on: ubuntu-latest
    environment:
      name: Production
    steps:
      - name: Deploy
        run: echo I am deploying to production

# Metrics
  Metrics:
    name: Metrics
    needs: [DeployProduction]
    runs-on: ubuntu-latest
    
    steps:
    - name: DORA deployment frequency
      uses: DeveloperMetrics/deployment-frequency@v1.5.22  
      with:
        workflows: 'CI CD Pipeline'
        default-branch: 'master'
    - name: DORA lead time for changes
      uses: DeveloperMetrics/lead-time-for-changes@v1.2.24
      with:
        workflows: 'CI CD Pipeline'
        default-branch: 'master'
