name: CI Pipeline

on:
  push:
    branches: [ "master", "feature-*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore BlazorWebAppGames.csproj

      - name: Build
        run: dotnet build BlazorWebAppGames.csproj --configuration Release --no-restore
